// Uncomment and fill out relevant fields to add support for a property
// Properties must be in the following format:
// (name, type, description, validation), where
// name (required) is a 4 character string,
// type (required) is a valid property type (str, dec, hex, log, mac, cfb, bin)
// description (required) is a short, one-line description of the property
// validation (optional) is eval()d to verify the input value for setting a property

const _props = {
    'buil': ['str', 'Build string?', undefined] as Prop<'str'>,
    'DynS': ['cfb', 'DNS', undefined] as Prop<'cfb'>,
    // 'cfpf': ['', '', undefined],
    // 'cloC': ['', '', undefined],
    // 'cloD': ['', '', undefined],
    // 'conf': ['', '', undefined],
    'fire': ['cfb', 'Firewall???', undefined] as Prop<'cfb'>,
    // 'prob': ['', '', undefined],
    'srcv': ['str', 'Source Version', undefined] as Prop<'str'>,
    'syNm': ['str', 'Device name', undefined] as Prop<'str'>,
    // 'syDN': ['', '', undefined],
    // 'syPI': ['', '', undefined],
    'syPW': ['str', 'Router administration password', undefined] as Prop<'str'>,
    'syPR': ['str', 'syPR string???', undefined] as Prop<'str'>,
    'syGP': ['str', 'Router guest password???', undefined] as Prop<'str'>,
    // 'syCt': ['', '', undefined],
    // 'syLo': ['', '', undefined],
    'syDs': ['str', 'System description', undefined] as Prop<'str'>,
    'syVs': ['str', 'System version', undefined] as Prop<'str'>,
    'syVr': ['str', 'System version???', undefined] as Prop<'str'>,
    'syIn': ['str', 'System information???', undefined] as Prop<'str'>,
    'syFl': ['hex', '????', undefined] as Prop<'hex'>,
    'syAM': ['str', 'Model Identifier', undefined] as Prop<'str'>,
    'syAP': ['dec', 'Product ID', undefined] as Prop<'dec'>,
    'sySN': ['str', 'Apple Serial Number', undefined] as Prop<'str'>,
    // 'ssSN': ['', '', undefined],
    // 'sySK': ['', '', undefined],
    'ssSK': ['str', 'Apple SKU', undefined] as Prop<'str'>,
    // 'syRe': ['', '', undefined],
    'syLR': ['cfb', 'syLR Blob', undefined] as Prop<'cfb'>,
    'syAR': ['cfb', 'syAR Blob', undefined] as Prop<'cfb'>,
    'syUT': ['dec', 'System Uptime', undefined] as Prop<'dec'>,
    // 'minV': ['', '', undefined],
    'minS': ['str', 'apple-minver', undefined] as Prop<'str'>,
    'chip': ['str', 'SoC Description', undefined] as Prop<'str'>,
    // 'card': ['', '', undefined],
    // 'memF': ['', '', undefined],
    // 'pool': ['', '', undefined],
    // 'tmpC': ['', '', undefined],
    // 'RPMs': ['', '', undefined],
    'sySI': ['cfb', 'System Info Blob?', undefined] as Prop<'cfb'>,
    // 'fDCY': ['', '', undefined],
    'TMEn': ['hex', 'TMEn???', undefined] as Prop<'hex'>,
    'CLTM': ['cfb', 'CLTM???', undefined] as Prop<'cfb'>,
    // 'sPLL': ['', '', undefined],
    // 'syTL': ['', '', undefined],
    // 'syST': ['', '', undefined],
    'sySt': ['cfb', 'System Status', undefined] as Prop<'cfb'>,
    // 'syIg': ['', '', undefined],
    'syBL': ['str', 'Bootloader vesrsion string', undefined] as Prop<'str'>,
    'time': ['dec', 'System time', undefined] as Prop<'dec'>,
    'timz': ['cfb', 'Timezone Config Blob', undefined] as Prop<'cfb'>,
    'usrd': ['cfb', 'usrd???', undefined] as Prop<'cfb'>,
    // 'uuid': ['', '', undefined],
    // 'drTY': ['', '', undefined],
    // 'sttE': ['', '', undefined],
    // 'sttF': ['', '', undefined],
    // 'stat': ['', '', undefined],
    // 'sRnd': ['', '', undefined],
    // 'Accl': ['', '', undefined],
    'dSpn': ['cfb', 'Disk spin status?', undefined] as Prop<'cfb'>,
    'syMS': ['str', 'MLB Serial Number', undefined] as Prop<'str'>,
    // 'IGMP': ['', '', undefined],
    'diag': ['bin', 'diag???', undefined] as Prop<'bin'>,
    // 'paFR': ['', '', undefined],
    'raNm': ['str', 'Radio Name', undefined] as Prop<'str'>,
    // 'raCl': ['', '', undefined],
    // 'raSk': ['', '', undefined],
    // 'raWM': ['', '', undefined],
    // 'raEA': ['', '', undefined],
    // 'raWE': ['', '', undefined],
    // 'raCr': ['', '', undefined],
    // 'raKT': ['', '', undefined],
    // 'raNN': ['', '', undefined],
    // 'raGK': ['', '', undefined],
    // 'raHW': ['', '', undefined],
    // 'raCM': ['', '', undefined],
    // 'raRo': ['', '', undefined],
    // 'raCA': ['', '', undefined],
    // 'raCh': ['', '', undefined],
    // 'rCh2': ['', '', undefined],
    // 'raWC': ['', '', undefined],
    // 'raDe': ['', '', undefined],
    // 'raMu': ['', '', undefined],
    // 'raLC': ['', '', undefined],
    // 'raLF': ['', '', undefined],
    // 'ra1C': ['', '', undefined],
    // 'raVs': ['', '', undefined],
    'raMA': ['mac', 'Radio MAC Address', undefined] as Prop<'mac'>,
    // 'raM2': ['', '', undefined],
    // 'raMO': ['', '', undefined],
    // 'raLO': ['', '', undefined],
    // 'raDS': ['', '', undefined],
    // 'raNA': ['', '', undefined],
    // 'raWB': ['', '', undefined],
    // 'raIS': ['', '', undefined],
    // 'raMd': ['', '', undefined],
    // 'raPo': ['', '', undefined],
    // 'raPx': ['', '', undefined],
    // 'raTr': ['', '', undefined],
    // 'raDt': ['', '', undefined],
    // 'raFC': ['', '', undefined],
    // 'raEC': ['', '', undefined],
    // 'raMX': ['', '', undefined],
    // 'raIE': ['', '', undefined],
    // 'raII': ['', '', undefined],
    // 'raB0': ['', '', undefined],
    // 'raB1': ['', '', undefined],
    // 'raB2': ['', '', undefined],
    // 'raSt': ['', '', undefined],
    // 'APSR': ['', '', undefined],
    // 'raTX': ['', '', undefined],
    // 'raRX': ['', '', undefined],
    // 'raAC': ['', '', undefined],
    'raSL': ['cfb', 'Radios list?', undefined] as Prop<'cfb'>,
    // 'raMI': ['', '', undefined],
    // 'raST': ['', '', undefined],
    // 'raDy': ['', '', undefined],
    // 'raEV': ['', '', undefined],
    // 'rTSN': ['', '', undefined],
    'raSR': ['cfb', 'Radio scan results?', undefined] as Prop<'cfb'>,
    // 'eaRA': ['', '', undefined],
    'WiFi': ['cfb', 'Wifi configuration?', undefined] as Prop<'cfb'>,
    'rCAL': ['cfb', 'Radio calibration data?', undefined] as Prop<'cfb'>,
    // 'moPN': ['', '', undefined],
    // 'moAP': ['', '', undefined],
    // 'moUN': ['', '', undefined],
    // 'moPW': ['', '', undefined],
    // 'moIS': ['', '', undefined],
    // 'moLS': ['', '', undefined],
    // 'moLI': ['', '', undefined],
    // 'moID': ['', '', undefined],
    // 'moDT': ['', '', undefined],
    // 'moPD': ['', '', undefined],
    // 'moAD': ['', '', undefined],
    // 'moCC': ['', '', undefined],
    // 'moCR': ['', '', undefined],
    // 'moCI': ['', '', undefined],
    // '^moM': ['', '', undefined],
    // 'moVs': ['', '', undefined],
    // 'moMP': ['', '', undefined],
    // 'moMF': ['', '', undefined],
    // 'moFV': ['', '', undefined],
    // 'pdFl': ['', '', undefined],
    // 'pdUN': ['', '', undefined],
    // 'pdPW': ['', '', undefined],
    // 'pdAR': ['', '', undefined],
    // 'pdID': ['', '', undefined],
    // 'pdMC': ['', '', undefined],
    // 'peSN': ['', '', undefined],
    // 'peUN': ['', '', undefined],
    // 'pePW': ['', '', undefined],
    // 'peSC': ['', '', undefined],
    // 'peAC': ['', '', undefined],
    // 'peID': ['', '', undefined],
    // 'peAO': ['', '', undefined],
    'waCV': ['bin', 'WAN Config Mode?', undefined] as Prop<'bin'>,
    'waIn': ['bin', 'WAN Interface Mode?', undefined] as Prop<'bin'>,
    // 'waD1': ['', '', undefined],
    // 'waD2': ['', '', undefined],
    // 'waD3': ['', '', undefined],
    // 'waC1': ['', '', undefined],
    // 'waC2': ['', '', undefined],
    // 'waC3': ['', '', undefined],
    'waIP': ['bin', 'WAN IP', undefined] as Prop<'bin'>,
    // 'waSM': ['', '', undefined],
    'waRA': ['bin', 'WAN Upstream Gateway IP', undefined] as Prop<'bin'>,
    // 'waDC': ['', '', undefined],
    // 'waDS': ['', '', undefined],
    'waMA': ['mac', 'WAN MAC Address', undefined] as Prop<'mac'>,
    // 'waMO': ['', '', undefined],
    // 'waDN': ['', '', undefined],
    // 'waCD': ['', '', undefined],
    // 'waIS': ['', '', undefined],
    // 'waNM': ['', '', undefined],
    // 'waSD': ['', '', undefined],
    // 'waFF': ['', '', undefined],
    // 'waRO': ['', '', undefined],
    // 'waW1': ['', '', undefined],
    // 'waW2': ['', '', undefined],
    // 'waW3': ['', '', undefined],
    // 'waLL': ['', '', undefined],
    // 'waUB': ['', '', undefined],
    'waDI': ['cfb', 'WAN DHCP Info?', undefined] as Prop<'cfb'>,
    // 'laCV': ['', '', undefined],
    // 'laIP': ['', '', undefined],
    // 'laSM': ['', '', undefined],
    // 'laRA': ['', '', undefined],
    // 'laDC': ['', '', undefined],
    // 'laDS': ['', '', undefined],
    // 'laNA': ['', '', undefined],
    'laMA': ['mac', 'LAN MAC Address', undefined] as Prop<'mac'>,
    // 'laIS': ['', '', undefined],
    // 'laSD': ['', '', undefined],
    // 'laIA': ['', '', undefined],
    // 'gn6?': ['', '', undefined],
    // 'gn6A': ['', '', undefined],
    // 'gn6P': ['', '', undefined],
    // 'dhFl': ['', '', undefined],
    // 'dhBg': ['', '', undefined],
    // 'dhEn': ['', '', undefined],
    // 'dhSN': ['', '', undefined],
    // 'dhRo': ['', '', undefined],
    // 'dhLe': ['', '', undefined],
    // 'dhMg': ['', '', undefined],
    // 'dh95': ['', '', undefined],
    'DRes': ['cfb', 'DHCP Reservations', undefined] as Prop<'cfb'>,
    // 'dhWA': ['', '', undefined],
    // 'dhDS': ['', '', undefined],
    // 'dhDB': ['', '', undefined],
    // 'dhDE': ['', '', undefined],
    // 'dhDL': ['', '', undefined],
    'dhSL': ['cfb', 'DHCP Server leases?', undefined] as Prop<'cfb'>,
    // 'gnFl': ['', '', undefined],
    // 'gnBg': ['', '', undefined],
    // 'gnEn': ['', '', undefined],
    // 'gnSN': ['', '', undefined],
    // 'gnRo': ['', '', undefined],
    // 'gnLe': ['', '', undefined],
    // 'gnMg': ['', '', undefined],
    // 'gn95': ['', '', undefined],
    // 'gnDi': ['', '', undefined],
    // 'naFl': ['', '', undefined],
    // 'naBg': ['', '', undefined],
    // 'naEn': ['', '', undefined],
    // 'naSN': ['', '', undefined],
    // 'naRo': ['', '', undefined],
    // 'naAF': ['', '', undefined],
    // 'nDMZ': ['', '', undefined],
    // 'pmPI': ['', '', undefined],
    // 'pmPS': ['', '', undefined],
    // 'pmPR': ['', '', undefined],
    // 'pmTa': ['', '', undefined],
    // 'acEn': ['', '', undefined],
    // 'acTa': ['', '', undefined],
    'tACL': ['cfb', 'Timed Access Control', undefined] as Prop<'cfb'>,
    // 'wdFl': ['', '', undefined],
    // 'wdLs': ['', '', undefined],
    // 'dWDS': ['', '', undefined],
    // 'cWDS': ['', '', undefined],
    // 'dwFl': ['', '', undefined],
    // 'raFl': ['', '', undefined],
    // 'raI1': ['', '', undefined],
    // 'raTm': ['', '', undefined],
    // 'raAu': ['', '', undefined],
    // 'raAc': ['', '', undefined],
    // 'raSe': ['', '', undefined],
    // 'raRe': ['', '', undefined],
    // 'raF2': ['', '', undefined],
    // 'raI2': ['', '', undefined],
    // 'raT2': ['', '', undefined],
    // 'raU2': ['', '', undefined],
    // 'raC2': ['', '', undefined],
    // 'raS2': ['', '', undefined],
    // 'raR2': ['', '', undefined],
    // 'raCi': ['', '', undefined],
    'ntSV': ['str', 'NTP Server Hostname', undefined] as Prop<'str'>,
    // 'ntpC': ['', '', undefined],
    // 'smtp': ['', '', undefined],
    // 'slog': ['', '', undefined],
    // 'slgC': ['', '', undefined],
    // 'slCl': ['', '', undefined],
    'slvl': ['dec', 'System log severity level?', undefined] as Prop<'dec'>,
    // 'slfl': ['', '', undefined],
    'logm': ['log', 'System log data', undefined] as Prop<'log'>,
    // 'snAF': ['', '', undefined],
    // 'snLW': ['', '', undefined],
    // 'snLL': ['', '', undefined],
    // 'snRW': ['', '', undefined],
    // 'snWW': ['', '', undefined],
    // 'snRL': ['', '', undefined],
    // 'snWL': ['', '', undefined],
    // 'snCS': ['', '', undefined],
    // 'srtA': ['', '', undefined],
    // 'srtF': ['', '', undefined],
    // 'upsF': ['', '', undefined],
    // 'usbF': ['', '', undefined],
    'USBi': ['cfb', 'USB Info', undefined] as Prop<'cfb'>,
    // 'USBL': ['', '', undefined],
    // 'USBR': ['', '', undefined],
    // 'USBO': ['', '', undefined],
    // 'USBs': ['', '', undefined],
    // 'USBo': ['', '', undefined],
    // 'USBh': ['', '', undefined],
    // 'USBb': ['', '', undefined],
    // 'USBn': ['', '', undefined],
    'prni': ['cfb', 'Printer Info?', undefined] as Prop<'cfb'>,
    // 'prnM': ['', '', undefined],
    // 'prnI': ['', '', undefined],
    // 'prnR': ['', '', undefined],
    // 'RUdv': ['', '', undefined],
    // 'RUfl': ['', '', undefined],
    'MaSt': ['cfb', 'USB Mass Storage Info', undefined] as Prop<'cfb'>,
    // 'SMBw': ['', '', undefined],
    // 'SMBs': ['', '', undefined],
    // 'fssp': ['', '', undefined],
    // 'diSD': ['', '', undefined],
    // 'diCS': ['', '', undefined],
    // 'deSt': ['', '', undefined],
    // 'daSt': ['', '', undefined],
    // 'dmSt': ['', '', undefined],
    // 'adNm': ['', '', undefined],
    // 'adBD': ['', '', undefined],
    // 'adAD': ['', '', undefined],
    // 'adHU': ['', '', undefined],
    // 'IDNm': ['', '', undefined],
    'seFl': ['bin', '????', undefined] as Prop<'bin'>, // ????
    // 'nvVs': ['', '', undefined],
    // 'dbRC': ['', '', undefined],
    'dbug': ['hex', 'Debug flags', (value: Buffer) => {
        const v = value.readUIntBE(0, value.length);
        return 0 <= v && v <= 0xffffffff;
    }] as Prop<'hex'>,
    // 'dlvl': ['', '', undefined],
    // 'dcmd': ['', '', undefined],
    // 'dsps': ['', '', undefined],
    // 'logC': ['', '', undefined],
    // 'cver': ['', '', undefined],
    'ctim': ['hex', 'ctim???', undefined] as Prop<'hex'>,
    // 'svMd': ['', '', undefined],
    // 'serM': ['', '', undefined],
    // 'serT': ['', '', undefined],
    // 'emNo': ['', '', undefined],
    // 'effF': ['', '', undefined],
    // 'LLnk': ['', '', undefined],
    // 'WLnk': ['', '', undefined],
    // 'PHYS': ['', '', undefined],
    // 'PHYN': ['', '', undefined],
    // 'Rnfo': ['', '', undefined],
    // 'evtL': ['', '', undefined],
    // 'isAC': ['', '', undefined],
    // 'Adet': ['', '', undefined],
    'Prof': ['cfb', 'Restore Profile Blob', undefined] as Prop<'cfb'>,
    // 'maAl': ['', '', undefined],
    // 'maPr': ['', '', undefined],
    // 'leAc': ['', '', undefined],
    // 'APID': ['', '', undefined],
    // 'AAU ': ['', '', undefined],
    'lcVs': ['str', 'lcVs Version String?', undefined] as Prop<'str'>,
    // 'lcVr': ['', '', undefined],
    // 'lcmV': ['', '', undefined],
    // 'lcMV': ['', '', undefined],
    // 'iMTU': ['', '', undefined],
    'wsci': ['cfb', 'wsci Blob', undefined] as Prop<'cfb'>,
    // 'FlSu': ['', '', undefined],
    'OTPR': ['hex', 'machdep.otpval', undefined] as Prop<'hex'>,
    'acRB': ['dec', 'Reboot device flag', (value: Buffer) => value.readUIntBE(0, value.length) === 0] as Prop<'dec'>,
    'acRI': ['dec', 'Reload services??', (value: Buffer) => value.readUIntBE(0, value.length) === 0] as Prop<'dec'>,
    // 'acPC': ['', '', undefined],
    // 'acDD': ['', '', undefined],
    // 'acPD': ['', '', undefined],
    // 'acPG': ['', '', undefined],
    // 'acDS': ['', '', undefined],
    // 'acFN': ['', '', undefined],
    // 'acRP': ['', '', undefined],
    'acRN': ['dec', 'Resets something... (?)', (value: Buffer) => {
        return value.readUIntBE(0, value.length) === 0;
    }] as Prop<'dec'>,
    'acRF': ['dec', 'Reset to factory defaults', (value: Buffer) => {
        return value.readUIntBE(0, value.length) === 0;
    }] as Prop<'dec'>,
    // 'MdmH': ['', '', undefined],
    // 'dirf': ['', '', undefined],
    // 'Afrc': ['', '', undefined],
    // 'lebl': ['', '', undefined],
    // 'lebs': ['', '', undefined],
    'LEDc': ['dec', 'LED color/pattern', (value: Buffer) => {
        const v = value.readUIntBE(0, value.length);
        return 0 <= v && v <= 3;
    }] as Prop<'dec'>,
    // 'acEf': ['', '', undefined],
    // 'invr': ['', '', undefined],
    // 'FLSH': ['', '', undefined],
    // 'acPL': ['', '', undefined],
    // 'rReg': ['', '', undefined],
    // 'dReg': ['', '', undefined],
    'GPIs': ['bin', 'GPIOs values', (value: Buffer) => value.length === 8] as Prop<'bin'>,
    // 'play': ['', '', undefined],
    // 'paus': ['', '', undefined],
    // 'ffwd': ['', '', undefined],
    // 'rwnd': ['', '', undefined],
    // 'itun': ['', '', undefined],
    // 'plls': ['', '', undefined],
    // 'User': ['', '', undefined],
    // 'Pass': ['', '', undefined],
    // 'itIP': ['', '', undefined],
    // 'itpt': ['', '', undefined],
    // 'daap': ['', '', undefined],
    // 'song': ['', '', undefined],
    // 'arti': ['', '', undefined],
    // 'albm': ['', '', undefined],
    // 'volm': ['', '', undefined],
    // 'rvol': ['', '', undefined],
    // 'Tcnt': ['', '', undefined],
    // 'Bcnt': ['', '', undefined],
    // 'shfl': ['', '', undefined],
    // 'rept': ['', '', undefined],
    // 'auPr': ['', '', undefined],
    // 'auJD': ['', '', undefined],
    // 'auNN': ['', '', undefined],
    // 'auNP': ['', '', undefined],
    // 'aFrq': ['', '', undefined],
    // 'aChn': ['', '', undefined],
    // 'aLvl': ['', '', undefined],
    // 'aPat': ['', '', undefined],
    // 'aSta': ['', '', undefined],
    // 'aStp': ['', '', undefined],
    // 'auCC': ['', '', undefined],
    // 'acmp': ['', '', undefined],
    // 'aenc': ['', '', undefined],
    // 'anBf': ['', '', undefined],
    // 'aWan': ['', '', undefined],
    // 'auRR': ['', '', undefined],
    // 'auMt': ['', '', undefined],
    // 'aDCP': ['', '', undefined],
    // 'DCPc': ['', '', undefined],
    // 'DACP': ['', '', undefined],
    // 'DCPi': ['', '', undefined],
    // 'auSl': ['', '', undefined],
    // 'auFl': ['', '', undefined],
    'fe01': ['hex', '????', undefined] as Prop<'hex'>,
    'feat': ['str', 'Supported features?', undefined] as Prop<'str'>,
    'prop': ['str', 'Valid acp properties', undefined] as Prop<'str'>,
    'hw01': ['hex', '????', undefined] as Prop<'hex'>,
    // 'fltr': ['', '', undefined],
    // 'wdel': ['', '', undefined],
    // 'plEB': ['', '', undefined],
    // 'rWSC': ['', '', undefined],
    // 'uDFS': ['', '', undefined],
    // 'dWPA': ['', '', undefined],
    // 'dpFF': ['', '', undefined],
    // 'duLF': ['', '', undefined],
    // 'ieHT': ['', '', undefined],
    // 'dwlX': ['', '', undefined],
    // 'dd11': ['', '', undefined],
    // 'dRdr': ['', '', undefined],
    // 'dotD': ['', '', undefined],
    // 'dotH': ['', '', undefined],
    // 'dPwr': ['', '', undefined],
    // 'wlBR': ['', '', undefined],
    // 'iTIM': ['', '', undefined],
    // 'idAG': ['', '', undefined],
    // 'mvFL': ['', '', undefined],
    // 'mvFM': ['', '', undefined],
    // 'dPPP': ['', '', undefined],
    // '!mta': ['', '', undefined],
    // 'minR': ['', '', undefined],
    // 'SpTr': ['', '', undefined],
    // 'dRBT': ['', '', undefined],
    // 'dRIR': ['', '', undefined],
    'pECC': ['cfb', 'PCIe ECC Blob?', undefined] as Prop<'cfb'>,
    // 'fxEB': ['', '', undefined],
    // 'fxID': ['', '', undefined],
    // 'fuup': ['', '', undefined],
    // 'fust': ['', '', undefined],
    // 'fuca': ['', '', undefined],
    'fugp': ['str', 'Firmware upgrade progress', undefined] as Prop<'str'>,
    'cks0': ['hex', 'Bootloader Flash Checksum', undefined] as Prop<'hex'>,
    'cks1': ['hex', 'Primary Flash Checksum', undefined] as Prop<'hex'>,
    'cks2': ['hex', 'Secondary Flash Checksum', undefined] as Prop<'hex'>,
    // 'ddBg': ['', '', undefined],
    // 'ddEn': ['', '', undefined],
    // 'ddIn': ['', '', undefined],
    // 'ddSm': ['', '', undefined],
    // 'ddEC': ['', '', undefined],
    // 'ddFE': ['', '', undefined],
    // 'ddSR': ['', '', undefined],
    // '6cfg': ['', '', undefined],
    // '6aut': ['', '', undefined],
    // '6Qpd': ['', '', undefined],
    // '6Wad': ['', '', undefined],
    // '6Wfx': ['', '', undefined],
    // '6Wgw': ['', '', undefined],
    // '6Wte': ['', '', undefined],
    // '6Lfw': ['', '', undefined],
    // '6Lad': ['', '', undefined],
    // '6Lfx': ['', '', undefined],
    // '6sfw': ['', '', undefined],
    // '6pmp': ['', '', undefined],
    // '6trd': ['', '', undefined],
    // '6sec': ['', '', undefined],
    // '6fwl': ['', '', undefined],
    // '6NS1': ['', '', undefined],
    // '6NS2': ['', '', undefined],
    // '6NS3': ['', '', undefined],
    // '6ahr': ['', '', undefined],
    // '6dhs': ['', '', undefined],
    // '6dso': ['', '', undefined],
    // '6PDa': ['', '', undefined],
    // '6PDl': ['', '', undefined],
    // '6vlt': ['', '', undefined],
    // '6plt': ['', '', undefined],
    // '6CWa': ['', '', undefined],
    // '6CWp': ['', '', undefined],
    // '6CWg': ['', '', undefined],
    // '6CLa': ['', '', undefined],
    // '6NSa': ['', '', undefined],
    // '6NSb': ['', '', undefined],
    // '6NSc': ['', '', undefined],
    // '6CPa': ['', '', undefined],
    // '6CPl': ['', '', undefined],
    // '6!at': ['', '', undefined],
    'rteI': ['cfb', 'rteI Blob', undefined] as Prop<'cfb'>,
    // 'PCLI': ['', '', undefined],
    // 'dxEM': ['', '', undefined],
    // 'dxID': ['', '', undefined],
    // 'dxAI': ['', '', undefined],
    // 'dxIP': ['', '', undefined],
    // 'dxOA': ['', '', undefined],
    // 'dxIA': ['', '', undefined],
    // 'dxC1': ['', '', undefined],
    // 'dxP1': ['', '', undefined],
    // 'dxC2': ['', '', undefined],
    // 'dxP2': ['', '', undefined],
    // 'bjFl': ['', '', undefined],
    // 'bjSd': ['', '', undefined],
    // 'bjSM': ['', '', undefined],
    // 'wbEn': ['', '', undefined],
    // 'wbHN': ['', '', undefined],
    // 'wbHU': ['', '', undefined],
    // 'wbHP': ['', '', undefined],
    // 'wbRD': ['', '', undefined],
    // 'wbRU': ['', '', undefined],
    // 'wbRP': ['', '', undefined],
    // 'wbAC': ['', '', undefined],
    // 'dMac': ['', '', undefined],
    // 'iCld': ['', '', undefined],
    // 'iCLH': ['', '', undefined],
    // 'iCLB': ['', '', undefined],
    // 'SUEn': ['', '', undefined],
    // 'SUAI': ['', '', undefined],
    // 'SUFq': ['', '', undefined],
    // 'SUSv': ['', '', undefined],
    // 'suPR': ['', '', undefined],
    // 'msEn': ['', '', undefined],
    // 'trCo': ['', '', undefined],
    // 'EZCF': ['', '', undefined],
    // 'ezcf': ['', '', undefined],
    // 'gVID': ['', '', undefined],
    // 'wcfg': ['', '', undefined],
    // 'awce': ['', '', undefined],
    // 'wcgu': ['', '', undefined],
    // 'wcgs': ['', '', undefined],
    // 'awcc': ['', '', undefined],
};

export type PropType = 'str' | 'dec' | 'hex' | 'log' | 'mac' | 'cfb' | 'bin';
type Validator = (value: Buffer, name: string) => boolean;

// type Prop = [PropType, string, Validator | undefined];
type Prop<T extends PropType = PropType> = [T, string, Validator | undefined];

export type PropName = keyof typeof _props;
export type PropTypes = {
    [N in PropName]: (typeof _props[N])[0];
};
const props: {
    [name: string]: Prop;
} = _props;

export default props;
