// Uncomment and fill out relevant fields to add support for a property
// Properties must be in the following format:
// (name, type, description, validation), where
// name (required) is a 4 character string,
// type (required) is a valid property type (str, dec, hex, log, mac, cfb, bin)
// description (required) is a short, one-line description of the property
// validation (optional) is eval()d to verify the input value for setting a property

type Validator = (value: any, name: string) => boolean;

type Prop = [string, PropType, string, Validator | undefined];

const props: Prop[] = [
    ['buil', 'str', 'Build string?', undefined],
    ['DynS', 'cfb', 'DNS', undefined],
    // ['cfpf', '', '', undefined],
    // ['cloC', '', '', undefined],
    // ['cloD', '', '', undefined],
    // ['conf', '', '', undefined],
    ['fire', 'cfb', 'Firewall???', undefined],
    // ['prob', '', '', undefined],
    ['srcv', 'str', 'Source Version', undefined],
    ['syNm', 'str', 'Device name', undefined],
    // ['syDN', '', '', undefined],
    // ['syPI', '', '', undefined],
    ['syPW', 'str', 'Router administration password', undefined],
    ['syPR', 'str', 'syPR string???', undefined],
    ['syGP', 'str', 'Router guest password???', undefined],
    // ['syCt', '', '', undefined],
    // ['syLo', '', '', undefined],
    ['syDs', 'str', 'System description', undefined],
    ['syVs', 'str', 'System version', undefined],
    ['syVr', 'str', 'System version???', undefined],
    ['syIn', 'str', 'System information???', undefined],
    ['syFl', 'hex', '????', undefined],
    ['syAM', 'str', 'Model Identifier', undefined],
    ['syAP', 'dec', 'Product ID', undefined],
    ['sySN', 'str', 'Apple Serial Number', undefined],
    // ['ssSN', '', '', undefined],
    // ['sySK', '', '', undefined],
    ['ssSK', 'str', 'Apple SKU', undefined],
    // ['syRe', '', '', undefined],
    ['syLR', 'cfb', 'syLR Blob', undefined],
    ['syAR', 'cfb', 'syAR Blob', undefined],
    ['syUT', 'dec', 'System Uptime', undefined],
    // ['minV', '', '', undefined],
    ['minS', 'str', 'apple-minver', undefined],
    ['chip', 'str', 'SoC Description', undefined],
    // ['card', '', '', undefined],
    // ['memF', '', '', undefined],
    // ['pool', '', '', undefined],
    // ['tmpC', '', '', undefined],
    // ['RPMs', '', '', undefined],
    ['sySI', 'cfb', 'System Info Blob?', undefined],
    // ['fDCY', '', '', undefined],
    ['TMEn', 'hex', 'TMEn???', undefined],
    ['CLTM', 'cfb', 'CLTM???', undefined],
    // ['sPLL', '', '', undefined],
    // ['syTL', '', '', undefined],
    // ['syST', '', '', undefined],
    ['sySt', 'cfb', 'System Status', undefined],
    // ['syIg', '', '', undefined],
    ['syBL', 'str', 'Bootloader vesrsion string', undefined],
    ['time', 'dec', 'System time', undefined],
    ['timz', 'cfb', 'Timezone Config Blob', undefined],
    ['usrd', 'cfb', 'usrd???', undefined],
    // ['uuid', '', '', undefined],
    // ['drTY', '', '', undefined],
    // ['sttE', '', '', undefined],
    // ['sttF', '', '', undefined],
    // ['stat', '', '', undefined],
    // ['sRnd', '', '', undefined],
    // ['Accl', '', '', undefined],
    ['dSpn', 'cfb', 'Disk spin status?', undefined],
    ['syMS', 'str', 'MLB Serial Number', undefined],
    // ['IGMP', '', '', undefined],
    ['diag', 'bin', 'diag???', undefined],
    // ['paFR', '', '', undefined],
    ['raNm', 'str', 'Radio Name', undefined],
    // ['raCl', '', '', undefined],
    // ['raSk', '', '', undefined],
    // ['raWM', '', '', undefined],
    // ['raEA', '', '', undefined],
    // ['raWE', '', '', undefined],
    // ['raCr', '', '', undefined],
    // ['raKT', '', '', undefined],
    // ['raNN', '', '', undefined],
    // ['raGK', '', '', undefined],
    // ['raHW', '', '', undefined],
    // ['raCM', '', '', undefined],
    // ['raRo', '', '', undefined],
    // ['raCA', '', '', undefined],
    // ['raCh', '', '', undefined],
    // ['rCh2', '', '', undefined],
    // ['raWC', '', '', undefined],
    // ['raDe', '', '', undefined],
    // ['raMu', '', '', undefined],
    // ['raLC', '', '', undefined],
    // ['raLF', '', '', undefined],
    // ['ra1C', '', '', undefined],
    // ['raVs', '', '', undefined],
    ['raMA', 'mac', 'Radio MAC Address', undefined],
    // ['raM2', '', '', undefined],
    // ['raMO', '', '', undefined],
    // ['raLO', '', '', undefined],
    // ['raDS', '', '', undefined],
    // ['raNA', '', '', undefined],
    // ['raWB', '', '', undefined],
    // ['raIS', '', '', undefined],
    // ['raMd', '', '', undefined],
    // ['raPo', '', '', undefined],
    // ['raPx', '', '', undefined],
    // ['raTr', '', '', undefined],
    // ['raDt', '', '', undefined],
    // ['raFC', '', '', undefined],
    // ['raEC', '', '', undefined],
    // ['raMX', '', '', undefined],
    // ['raIE', '', '', undefined],
    // ['raII', '', '', undefined],
    // ['raB0', '', '', undefined],
    // ['raB1', '', '', undefined],
    // ['raB2', '', '', undefined],
    // ['raSt', '', '', undefined],
    // ['APSR', '', '', undefined],
    // ['raTX', '', '', undefined],
    // ['raRX', '', '', undefined],
    // ['raAC', '', '', undefined],
    ['raSL', 'cfb', 'Radios list?', undefined],
    // ['raMI', '', '', undefined],
    // ['raST', '', '', undefined],
    // ['raDy', '', '', undefined],
    // ['raEV', '', '', undefined],
    // ['rTSN', '', '', undefined],
    ['raSR', 'cfb', 'Radio scan results?', undefined],
    // ['eaRA', '', '', undefined],
    ['WiFi', 'cfb', 'Wifi configuration?', undefined],
    ['rCAL', 'cfb', 'Radio calibration data?', undefined],
    // ['moPN', '', '', undefined],
    // ['moAP', '', '', undefined],
    // ['moUN', '', '', undefined],
    // ['moPW', '', '', undefined],
    // ['moIS', '', '', undefined],
    // ['moLS', '', '', undefined],
    // ['moLI', '', '', undefined],
    // ['moID', '', '', undefined],
    // ['moDT', '', '', undefined],
    // ['moPD', '', '', undefined],
    // ['moAD', '', '', undefined],
    // ['moCC', '', '', undefined],
    // ['moCR', '', '', undefined],
    // ['moCI', '', '', undefined],
    // ['^moM', '', '', undefined],
    // ['moVs', '', '', undefined],
    // ['moMP', '', '', undefined],
    // ['moMF', '', '', undefined],
    // ['moFV', '', '', undefined],
    // ['pdFl', '', '', undefined],
    // ['pdUN', '', '', undefined],
    // ['pdPW', '', '', undefined],
    // ['pdAR', '', '', undefined],
    // ['pdID', '', '', undefined],
    // ['pdMC', '', '', undefined],
    // ['peSN', '', '', undefined],
    // ['peUN', '', '', undefined],
    // ['pePW', '', '', undefined],
    // ['peSC', '', '', undefined],
    // ['peAC', '', '', undefined],
    // ['peID', '', '', undefined],
    // ['peAO', '', '', undefined],
    ['waCV', 'bin', 'WAN Config Mode?', undefined],
    ['waIn', 'bin', 'WAN Interface Mode?', undefined],
    // ['waD1', '', '', undefined],
    // ['waD2', '', '', undefined],
    // ['waD3', '', '', undefined],
    // ['waC1', '', '', undefined],
    // ['waC2', '', '', undefined],
    // ['waC3', '', '', undefined],
    ['waIP', 'bin', 'WAN IP', undefined],
    // ['waSM', '', '', undefined],
    ['waRA', 'bin', 'WAN Upstream Gateway IP', undefined],
    // ['waDC', '', '', undefined],
    // ['waDS', '', '', undefined],
    ['waMA', 'mac', 'WAN MAC Address', undefined],
    // ['waMO', '', '', undefined],
    // ['waDN', '', '', undefined],
    // ['waCD', '', '', undefined],
    // ['waIS', '', '', undefined],
    // ['waNM', '', '', undefined],
    // ['waSD', '', '', undefined],
    // ['waFF', '', '', undefined],
    // ['waRO', '', '', undefined],
    // ['waW1', '', '', undefined],
    // ['waW2', '', '', undefined],
    // ['waW3', '', '', undefined],
    // ['waLL', '', '', undefined],
    // ['waUB', '', '', undefined],
    ['waDI', 'cfb', 'WAN DHCP Info?', undefined],
    // ['laCV', '', '', undefined],
    // ['laIP', '', '', undefined],
    // ['laSM', '', '', undefined],
    // ['laRA', '', '', undefined],
    // ['laDC', '', '', undefined],
    // ['laDS', '', '', undefined],
    // ['laNA', '', '', undefined],
    ['laMA', 'mac', 'LAN MAC Address', undefined],
    // ['laIS', '', '', undefined],
    // ['laSD', '', '', undefined],
    // ['laIA', '', '', undefined],
    // ['gn6?', '', '', undefined],
    // ['gn6A', '', '', undefined],
    // ['gn6P', '', '', undefined],
    // ['dhFl', '', '', undefined],
    // ['dhBg', '', '', undefined],
    // ['dhEn', '', '', undefined],
    // ['dhSN', '', '', undefined],
    // ['dhRo', '', '', undefined],
    // ['dhLe', '', '', undefined],
    // ['dhMg', '', '', undefined],
    // ['dh95', '', '', undefined],
    ['DRes', 'cfb', 'DHCP Reservations', undefined],
    // ['dhWA', '', '', undefined],
    // ['dhDS', '', '', undefined],
    // ['dhDB', '', '', undefined],
    // ['dhDE', '', '', undefined],
    // ['dhDL', '', '', undefined],
    ['dhSL', 'cfb', 'DHCP Server leases?', undefined],
    // ['gnFl', '', '', undefined],
    // ['gnBg', '', '', undefined],
    // ['gnEn', '', '', undefined],
    // ['gnSN', '', '', undefined],
    // ['gnRo', '', '', undefined],
    // ['gnLe', '', '', undefined],
    // ['gnMg', '', '', undefined],
    // ['gn95', '', '', undefined],
    // ['gnDi', '', '', undefined],
    // ['naFl', '', '', undefined],
    // ['naBg', '', '', undefined],
    // ['naEn', '', '', undefined],
    // ['naSN', '', '', undefined],
    // ['naRo', '', '', undefined],
    // ['naAF', '', '', undefined],
    // ['nDMZ', '', '', undefined],
    // ['pmPI', '', '', undefined],
    // ['pmPS', '', '', undefined],
    // ['pmPR', '', '', undefined],
    // ['pmTa', '', '', undefined],
    // ['acEn', '', '', undefined],
    // ['acTa', '', '', undefined],
    ['tACL', 'cfb', 'Timed Access Control', undefined],
    // ['wdFl', '', '', undefined],
    // ['wdLs', '', '', undefined],
    // ['dWDS', '', '', undefined],
    // ['cWDS', '', '', undefined],
    // ['dwFl', '', '', undefined],
    // ['raFl', '', '', undefined],
    // ['raI1', '', '', undefined],
    // ['raTm', '', '', undefined],
    // ['raAu', '', '', undefined],
    // ['raAc', '', '', undefined],
    // ['raSe', '', '', undefined],
    // ['raRe', '', '', undefined],
    // ['raF2', '', '', undefined],
    // ['raI2', '', '', undefined],
    // ['raT2', '', '', undefined],
    // ['raU2', '', '', undefined],
    // ['raC2', '', '', undefined],
    // ['raS2', '', '', undefined],
    // ['raR2', '', '', undefined],
    // ['raCi', '', '', undefined],
    ['ntSV', 'str', 'NTP Server Hostname', undefined],
    // ['ntpC', '', '', undefined],
    // ['smtp', '', '', undefined],
    // ['slog', '', '', undefined],
    // ['slgC', '', '', undefined],
    // ['slCl', '', '', undefined],
    ['slvl', 'dec', 'System log severity level?', undefined],
    // ['slfl', '', '', undefined],
    ['logm', 'log', 'System log data', undefined],
    // ['snAF', '', '', undefined],
    // ['snLW', '', '', undefined],
    // ['snLL', '', '', undefined],
    // ['snRW', '', '', undefined],
    // ['snWW', '', '', undefined],
    // ['snRL', '', '', undefined],
    // ['snWL', '', '', undefined],
    // ['snCS', '', '', undefined],
    // ['srtA', '', '', undefined],
    // ['srtF', '', '', undefined],
    // ['upsF', '', '', undefined],
    // ['usbF', '', '', undefined],
    ['USBi', 'cfb', 'USB Info', undefined],
    // ['USBL', '', '', undefined],
    // ['USBR', '', '', undefined],
    // ['USBO', '', '', undefined],
    // ['USBs', '', '', undefined],
    // ['USBo', '', '', undefined],
    // ['USBh', '', '', undefined],
    // ['USBb', '', '', undefined],
    // ['USBn', '', '', undefined],
    ['prni', 'cfb', 'Printer Info?', undefined],
    // ['prnM', '', '', undefined],
    // ['prnI', '', '', undefined],
    // ['prnR', '', '', undefined],
    // ['RUdv', '', '', undefined],
    // ['RUfl', '', '', undefined],
    ['MaSt', 'cfb', 'USB Mass Storage Info', undefined],
    // ['SMBw', '', '', undefined],
    // ['SMBs', '', '', undefined],
    // ['fssp', '', '', undefined],
    // ['diSD', '', '', undefined],
    // ['diCS', '', '', undefined],
    // ['deSt', '', '', undefined],
    // ['daSt', '', '', undefined],
    // ['dmSt', '', '', undefined],
    // ['adNm', '', '', undefined],
    // ['adBD', '', '', undefined],
    // ['adAD', '', '', undefined],
    // ['adHU', '', '', undefined],
    // ['IDNm', '', '', undefined],
    ['seFl', 'bin', '????', undefined], // ????
    // ['nvVs', '', '', undefined],
    // ['dbRC', '', '', undefined],
    // @ts-ignore
    ['dbug', 'hex', 'Debug flags', value => 0 <= value <= 0xffffffff],
    // ['dlvl', '', '', undefined],
    // ['dcmd', '', '', undefined],
    // ['dsps', '', '', undefined],
    // ['logC', '', '', undefined],
    // ['cver', '', '', undefined],
    ['ctim', 'hex', 'ctim???', undefined],
    // ['svMd', '', '', undefined],
    // ['serM', '', '', undefined],
    // ['serT', '', '', undefined],
    // ['emNo', '', '', undefined],
    // ['effF', '', '', undefined],
    // ['LLnk', '', '', undefined],
    // ['WLnk', '', '', undefined],
    // ['PHYS', '', '', undefined],
    // ['PHYN', '', '', undefined],
    // ['Rnfo', '', '', undefined],
    // ['evtL', '', '', undefined],
    // ['isAC', '', '', undefined],
    // ['Adet', '', '', undefined],
    ['Prof', 'cfb', 'Restore Profile Blob', undefined],
    // ['maAl', '', '', undefined],
    // ['maPr', '', '', undefined],
    // ['leAc', '', '', undefined],
    // ['APID', '', '', undefined],
    // ['AAU ', '', '', undefined],
    ['lcVs', 'str', 'lcVs Version String?', undefined],
    // ['lcVr', '', '', undefined],
    // ['lcmV', '', '', undefined],
    // ['lcMV', '', '', undefined],
    // ['iMTU', '', '', undefined],
    ['wsci', 'cfb', 'wsci Blob', undefined],
    // ['FlSu', '', '', undefined],
    ['OTPR', 'hex', 'machdep.otpval', undefined],
    ['acRB', 'dec', 'Reboot device flag', value => value == 0],
    ['acRI', 'dec', 'Reload services??', value => value == 0],
    // ['acPC', '', '', undefined],
    // ['acDD', '', '', undefined],
    // ['acPD', '', '', undefined],
    // ['acPG', '', '', undefined],
    // ['acDS', '', '', undefined],
    // ['acFN', '', '', undefined],
    // ['acRP', '', '', undefined],
    ['acRN', 'dec', 'Resets something... (?)', value => value === 0],
    ['acRF', 'dec', 'Reset to factory defaults', value => value === 0],
    // ['MdmH', '', '', undefined],
    // ['dirf', '', '', undefined],
    // ['Afrc', '', '', undefined],
    // ['lebl', '', '', undefined],
    // ['lebs', '', '', undefined],
    // @ts-ignore
    ['LEDc', 'dec', 'LED color/pattern', value => 0 <= value <= 3],
    // ['acEf', '', '', undefined],
    // ['invr', '', '', undefined],
    // ['FLSH', '', '', undefined],
    // ['acPL', '', '', undefined],
    // ['rReg', '', '', undefined],
    // ['dReg', '', '', undefined],
    ['GPIs', 'bin', 'GPIOs values', value => value.length === 8],
    // ['play', '', '', undefined],
    // ['paus', '', '', undefined],
    // ['ffwd', '', '', undefined],
    // ['rwnd', '', '', undefined],
    // ['itun', '', '', undefined],
    // ['plls', '', '', undefined],
    // ['User', '', '', undefined],
    // ['Pass', '', '', undefined],
    // ['itIP', '', '', undefined],
    // ['itpt', '', '', undefined],
    // ['daap', '', '', undefined],
    // ['song', '', '', undefined],
    // ['arti', '', '', undefined],
    // ['albm', '', '', undefined],
    // ['volm', '', '', undefined],
    // ['rvol', '', '', undefined],
    // ['Tcnt', '', '', undefined],
    // ['Bcnt', '', '', undefined],
    // ['shfl', '', '', undefined],
    // ['rept', '', '', undefined],
    // ['auPr', '', '', undefined],
    // ['auJD', '', '', undefined],
    // ['auNN', '', '', undefined],
    // ['auNP', '', '', undefined],
    // ['aFrq', '', '', undefined],
    // ['aChn', '', '', undefined],
    // ['aLvl', '', '', undefined],
    // ['aPat', '', '', undefined],
    // ['aSta', '', '', undefined],
    // ['aStp', '', '', undefined],
    // ['auCC', '', '', undefined],
    // ['acmp', '', '', undefined],
    // ['aenc', '', '', undefined],
    // ['anBf', '', '', undefined],
    // ['aWan', '', '', undefined],
    // ['auRR', '', '', undefined],
    // ['auMt', '', '', undefined],
    // ['aDCP', '', '', undefined],
    // ['DCPc', '', '', undefined],
    // ['DACP', '', '', undefined],
    // ['DCPi', '', '', undefined],
    // ['auSl', '', '', undefined],
    // ['auFl', '', '', undefined],
    ['fe01', 'hex', '????', undefined],
    ['feat', 'str', 'Supported features?', undefined],
    ['prop', 'str', 'Valid acp properties', undefined],
    ['hw01', 'hex', '????', undefined],
    // ['fltr', '', '', undefined],
    // ['wdel', '', '', undefined],
    // ['plEB', '', '', undefined],
    // ['rWSC', '', '', undefined],
    // ['uDFS', '', '', undefined],
    // ['dWPA', '', '', undefined],
    // ['dpFF', '', '', undefined],
    // ['duLF', '', '', undefined],
    // ['ieHT', '', '', undefined],
    // ['dwlX', '', '', undefined],
    // ['dd11', '', '', undefined],
    // ['dRdr', '', '', undefined],
    // ['dotD', '', '', undefined],
    // ['dotH', '', '', undefined],
    // ['dPwr', '', '', undefined],
    // ['wlBR', '', '', undefined],
    // ['iTIM', '', '', undefined],
    // ['idAG', '', '', undefined],
    // ['mvFL', '', '', undefined],
    // ['mvFM', '', '', undefined],
    // ['dPPP', '', '', undefined],
    // ['!mta', '', '', undefined],
    // ['minR', '', '', undefined],
    // ['SpTr', '', '', undefined],
    // ['dRBT', '', '', undefined],
    // ['dRIR', '', '', undefined],
    ['pECC', 'cfb', 'PCIe ECC Blob?', undefined],
    // ['fxEB', '', '', undefined],
    // ['fxID', '', '', undefined],
    // ['fuup', '', '', undefined],
    // ['fust', '', '', undefined],
    // ['fuca', '', '', undefined],
    ['fugp', 'str', 'Firmware upgrade progress', undefined],
    ['cks0', 'hex', 'Bootloader Flash Checksum', undefined],
    ['cks1', 'hex', 'Primary Flash Checksum', undefined],
    ['cks2', 'hex', 'Secondary Flash Checksum', undefined],
    // ['ddBg', '', '', undefined],
    // ['ddEn', '', '', undefined],
    // ['ddIn', '', '', undefined],
    // ['ddSm', '', '', undefined],
    // ['ddEC', '', '', undefined],
    // ['ddFE', '', '', undefined],
    // ['ddSR', '', '', undefined],
    // ['6cfg', '', '', undefined],
    // ['6aut', '', '', undefined],
    // ['6Qpd', '', '', undefined],
    // ['6Wad', '', '', undefined],
    // ['6Wfx', '', '', undefined],
    // ['6Wgw', '', '', undefined],
    // ['6Wte', '', '', undefined],
    // ['6Lfw', '', '', undefined],
    // ['6Lad', '', '', undefined],
    // ['6Lfx', '', '', undefined],
    // ['6sfw', '', '', undefined],
    // ['6pmp', '', '', undefined],
    // ['6trd', '', '', undefined],
    // ['6sec', '', '', undefined],
    // ['6fwl', '', '', undefined],
    // ['6NS1', '', '', undefined],
    // ['6NS2', '', '', undefined],
    // ['6NS3', '', '', undefined],
    // ['6ahr', '', '', undefined],
    // ['6dhs', '', '', undefined],
    // ['6dso', '', '', undefined],
    // ['6PDa', '', '', undefined],
    // ['6PDl', '', '', undefined],
    // ['6vlt', '', '', undefined],
    // ['6plt', '', '', undefined],
    // ['6CWa', '', '', undefined],
    // ['6CWp', '', '', undefined],
    // ['6CWg', '', '', undefined],
    // ['6CLa', '', '', undefined],
    // ['6NSa', '', '', undefined],
    // ['6NSb', '', '', undefined],
    // ['6NSc', '', '', undefined],
    // ['6CPa', '', '', undefined],
    // ['6CPl', '', '', undefined],
    // ['6!at', '', '', undefined],
    ['rteI', 'cfb', 'rteI Blob', undefined],
    // ['PCLI', '', '', undefined],
    // ['dxEM', '', '', undefined],
    // ['dxID', '', '', undefined],
    // ['dxAI', '', '', undefined],
    // ['dxIP', '', '', undefined],
    // ['dxOA', '', '', undefined],
    // ['dxIA', '', '', undefined],
    // ['dxC1', '', '', undefined],
    // ['dxP1', '', '', undefined],
    // ['dxC2', '', '', undefined],
    // ['dxP2', '', '', undefined],
    // ['bjFl', '', '', undefined],
    // ['bjSd', '', '', undefined],
    // ['bjSM', '', '', undefined],
    // ['wbEn', '', '', undefined],
    // ['wbHN', '', '', undefined],
    // ['wbHU', '', '', undefined],
    // ['wbHP', '', '', undefined],
    // ['wbRD', '', '', undefined],
    // ['wbRU', '', '', undefined],
    // ['wbRP', '', '', undefined],
    // ['wbAC', '', '', undefined],
    // ['dMac', '', '', undefined],
    // ['iCld', '', '', undefined],
    // ['iCLH', '', '', undefined],
    // ['iCLB', '', '', undefined],
    // ['SUEn', '', '', undefined],
    // ['SUAI', '', '', undefined],
    // ['SUFq', '', '', undefined],
    // ['SUSv', '', '', undefined],
    // ['suPR', '', '', undefined],
    // ['msEn', '', '', undefined],
    // ['trCo', '', '', undefined],
    // ['EZCF', '', '', undefined],
    // ['ezcf', '', '', undefined],
    // ['gVID', '', '', undefined],
    // ['wcfg', '', '', undefined],
    // ['awce', '', '', undefined],
    // ['wcgu', '', '', undefined],
    // ['wcgs', '', '', undefined],
    // ['awcc', '', '', undefined],
];

export default props;

export type PropTypes = {
    'buil': 'str';
    'DynS': 'cfb';
    'fire': 'cfb';
    'srcv': 'str';
    'syNm': 'str';
    'syPW': 'str';
    'syPR': 'str';
    'syGP': 'str';
    'syDs': 'str';
    'syVs': 'str';
    'syVr': 'str';
    'syIn': 'str';
    'syFl': 'hex';
    'syAM': 'str';
    'syAP': 'dec';
    'sySN': 'str';
    'ssSK': 'str';
    'syLR': 'cfb';
    'syAR': 'cfb';
    'syUT': 'dec';
    'minS': 'str';
    'chip': 'str';
    'sySI': 'cfb';
    'TMEn': 'hex';
    'CLTM': 'cfb';
    'sySt': 'cfb';
    'syBL': 'str';
    'time': 'dec';
    'timz': 'cfb';
    'usrd': 'cfb';
    'dSpn': 'cfb';
    'syMS': 'str';
    'diag': 'bin';
    'raNm': 'str';
    'raMA': 'mac';
    'raSL': 'cfb';
    'raSR': 'cfb';
    'WiFi': 'cfb';
    'rCAL': 'cfb';
    'waCV': 'bin';
    'waIn': 'bin';
    'waIP': 'bin';
    'waRA': 'bin';
    'waMA': 'mac';
    'waDI': 'cfb';
    'laMA': 'mac';
    'DRes': 'cfb';
    'dhSL': 'cfb';
    'tACL': 'cfb';
    'ntSV': 'str';
    'slvl': 'dec';
    'logm': 'log';
    'USBi': 'cfb';
    'prni': 'cfb';
    'MaSt': 'cfb';
    'seFl': 'bin';
    'dbug': 'hex';
    'ctim': 'hex';
    'Prof': 'cfb';
    'lcVs': 'str';
    'wsci': 'cfb';
    'OTPR': 'hex';
    'acRB': 'dec';
    'acRI': 'dec';
    'acRN': 'dec';
    'acRF': 'dec';
    'LEDc': 'dec';
    'GPIs': 'bin';
    'fe01': 'hex';
    'feat': 'str';
    'prop': 'str';
    'hw01': 'hex';
    'pECC': 'cfb';
    'fugp': 'str';
    'cks0': 'hex';
    'cks1': 'hex';
    'cks2': 'hex';
    'rteI': 'cfb';
};

export type PropName = keyof PropTypes;
export type PropType = 'str' | 'dec' | 'hex' | 'log' | 'mac' | 'cfb' | 'bin';
